import { Category } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'home-personal',
    name: 'Home & Personal Services',
    tagline: 'Skilled technicians, repair services, and domestic assistance',
    iconName: 'Wrench',
    colorScheme: {
      bg: 'bg-blue-50',
      text: 'text-blue-700',
      border: 'border-blue-200',
      badge: 'bg-blue-100 text-blue-800',
      accent: 'from-blue-600 to-indigo-600',
    },
    subcategories: [
      { id: 'ac-repair', name: 'AC Repair', description: 'Cooling issues, gas refilling, compressor repair & seasonal servicing', type: 'service', estimatedResolutionTime: '2-4 hours', departmentOrIndustry: 'HVAC Services' },
      { id: 'refrigerator-repair', name: 'Refrigerator Repair', description: 'Freezer failure, defrosting issues, thermostat & compressor fixes', type: 'service', estimatedResolutionTime: '3-6 hours', departmentOrIndustry: 'Appliance Repair' },
      { id: 'washing-machine', name: 'Washing Machine Repair', description: 'Drum vibration, motor issues, drainage blockages & circuit faults', type: 'service', estimatedResolutionTime: 'Same day', departmentOrIndustry: 'Appliance Repair' },
      { id: 'electrician', name: 'Electrician', description: 'Short circuits, fuse replacement, rewiring, switches & inverter setup', type: 'service', estimatedResolutionTime: '1-2 hours', departmentOrIndustry: 'Electrical Services' },
      { id: 'plumber', name: 'Plumber', description: 'Leaking pipes, tap repairs, clogged drains, geyser fitting & sanitary fixes', type: 'service', estimatedResolutionTime: '1-3 hours', departmentOrIndustry: 'Plumbing Services' },
      { id: 'carpenter', name: 'Carpenter', description: 'Door locks, furniture assembly, hinge fixes & woodwork customization', type: 'service', estimatedResolutionTime: '2-5 hours', departmentOrIndustry: 'Woodwork' },
      { id: 'painter', name: 'Painter', description: 'Interior/exterior whitewash, waterproofing, texture & touch-up painting', type: 'service', estimatedResolutionTime: '1-3 days', departmentOrIndustry: 'Home Renovation' },
      { id: 'cook', name: 'Cook', description: 'Trained home chefs, meal preparations, daily cooks & party catering', type: 'service', estimatedResolutionTime: 'Same day', departmentOrIndustry: 'Domestic Staffing' },
      { id: 'cleaner', name: 'Cleaner', description: 'Deep home cleaning, bathroom sanitization, sofa/carpet shampooing', type: 'service', estimatedResolutionTime: '2-4 hours', departmentOrIndustry: 'Cleaning Services' },
      { id: 'gas-assistance', name: 'Gas-related assistance', description: 'Cylinder delivery delay, stove leakage, regulator & pipeline checks', type: 'service', estimatedResolutionTime: 'Immediate', departmentOrIndustry: 'LPG / Gas Supply' },
      { id: 'appliance-repair', name: 'Appliance Repair', description: 'Microwaves, water purifiers (RO), geysers, chimney & mixer repairs', type: 'service', estimatedResolutionTime: 'Same day', departmentOrIndustry: 'Appliance Repair' },
      { id: 'other-home', name: 'Other Home Services', description: 'Pest control, locksmith, window glass replacement & gardening', type: 'service', estimatedResolutionTime: 'Within 24 hours', departmentOrIndustry: 'General Home Support' },
    ],
  },
  {
    id: 'education',
    name: 'Education',
    tagline: 'Institutional concerns, scholarships, admissions & certificates',
    iconName: 'GraduationCap',
    colorScheme: {
      bg: 'bg-emerald-50',
      text: 'text-emerald-700',
      border: 'border-emerald-200',
      badge: 'bg-emerald-100 text-emerald-800',
      accent: 'from-emerald-600 to-teal-600',
    },
    subcategories: [
      { id: 'school-problems', name: 'School Problems', description: 'Classroom conditions, curriculum issues, faculty absence or fee disputes', type: 'education', estimatedResolutionTime: '2-3 days', departmentOrIndustry: 'School Education Dept' },
      { id: 'college-problems', name: 'College Problems', description: 'Lab facilities, library access, semester scheduling & hostel grievances', type: 'education', estimatedResolutionTime: '3-5 days', departmentOrIndustry: 'Higher Education' },
      { id: 'university-problems', name: 'University Problems', description: 'Affiliation, degree issuance, backlog re-evaluations & campus rights', type: 'education', estimatedResolutionTime: '5-7 days', departmentOrIndustry: 'University Affairs' },
      { id: 'government-school', name: 'Government School', description: 'Mid-day meals, free textbooks, teacher vacancies & sanitation issues', type: 'education', estimatedResolutionTime: '48 hours', departmentOrIndustry: 'State Education Board' },
      { id: 'private-school', name: 'Private School', description: 'Arbitrary fee escalations, safety norms, transport regulation complaints', type: 'education', estimatedResolutionTime: '3-4 days', departmentOrIndustry: 'Education Inspectorate' },
      { id: 'scholarship-problems', name: 'Scholarship Problems', description: 'Pending disbursements, portal verification errors & merit list queries', type: 'education', estimatedResolutionTime: '3-5 days', departmentOrIndustry: 'Scholarship Welfare Cell' },
      { id: 'admission-problems', name: 'Admission Problems', description: 'Quota allotment, document validation, counseling delays & seat disputes', type: 'education', estimatedResolutionTime: '24-48 hours', departmentOrIndustry: 'Admissions Council' },
      { id: 'examination-problems', name: 'Examination Problems', description: 'Admit card discrepancies, center allotment, paper recheck requests', type: 'education', estimatedResolutionTime: '24-48 hours', departmentOrIndustry: 'Exam Directorate' },
      { id: 'certificate-document', name: 'Certificate/Document Problems', description: 'Duplicate marksheet, transfer certificate (TC), migration & name correction', type: 'education', estimatedResolutionTime: '3-5 days', departmentOrIndustry: 'Academic Records Dept' },
      { id: 'teacher-institution', name: 'Teacher/Institution-related Issues', description: 'Harassment prevention, unfair grading, attendance disputes & ethics', type: 'education', estimatedResolutionTime: '48 hours', departmentOrIndustry: 'Grievance Redressal Committee' },
    ],
  },
  {
    id: 'public-infrastructure',
    name: 'Public Infrastructure',
    tagline: 'Civic amenities, road maintenance, streetlights & sanitation',
    iconName: 'Landmark',
    colorScheme: {
      bg: 'bg-amber-50',
      text: 'text-amber-700',
      border: 'border-amber-200',
      badge: 'bg-amber-100 text-amber-800',
      accent: 'from-amber-600 to-orange-600',
    },
    subcategories: [
      { id: 'road-problems', name: 'Road Problems', description: 'Damaged road surface, missing divider markings, sunken manholes', type: 'public_issue', estimatedResolutionTime: '3-7 days', departmentOrIndustry: 'Public Works Dept (PWD)' },
      { id: 'street-problems', name: 'Street Problems', description: 'Narrow alley blockages, unauthorized road encroachment & debris piles', type: 'public_issue', estimatedResolutionTime: '2-4 days', departmentOrIndustry: 'Municipal Corporation' },
      { id: 'potholes', name: 'Potholes', description: 'Hazardous road craters endangering commuters, two-wheelers & pedestrians', type: 'public_issue', estimatedResolutionTime: '48-72 hours', departmentOrIndustry: 'Roads & Bridges Wing' },
      { id: 'drainage', name: 'Drainage', description: 'Blocked storm-water drains causing monsoon waterlogging & overflow', type: 'public_issue', estimatedResolutionTime: '24-48 hours', departmentOrIndustry: 'Drainage Division' },
      { id: 'sewer-problems', name: 'Sewer Problems', description: 'Sewer pipeline overflow, foul odor & hazardous open manholes', type: 'public_issue', estimatedResolutionTime: '12-24 hours', departmentOrIndustry: 'Sewerage Board' },
      { id: 'water-supply', name: 'Water Supply', description: 'No municipal water supply, low water pressure, contaminated or muddy water', type: 'public_issue', estimatedResolutionTime: '12-24 hours', departmentOrIndustry: 'Jal Board / Water Dept' },
      { id: 'street-lights', name: 'Street Lights', description: 'Non-functional street lamps creating dark blindspots & safety risks', type: 'public_issue', estimatedResolutionTime: '24-48 hours', departmentOrIndustry: 'Electrical Municipal Wing' },
      { id: 'public-cleanliness', name: 'Public Cleanliness', description: 'Unswept public walkways, park upkeep, stray animal nuisances', type: 'public_issue', estimatedResolutionTime: '24 hours', departmentOrIndustry: 'Sanitation Dept' },
      { id: 'garbage-sanitation', name: 'Garbage/Sanitation', description: 'Uncollected community dumpsters, littering hotspots & bin overflows', type: 'public_issue', estimatedResolutionTime: '12-24 hours', departmentOrIndustry: 'Waste Management Wing' },
      { id: 'public-facilities', name: 'Public Facilities', description: 'Broken park benches, dilapidated community halls, open gym repairs', type: 'public_issue', estimatedResolutionTime: '3-5 days', departmentOrIndustry: 'Urban Development' },
    ],
  },
  {
    id: 'transportation',
    name: 'Transportation',
    tagline: 'Railways, bus terminals, public transit & commute infrastructure',
    iconName: 'TrainTrack',
    colorScheme: {
      bg: 'bg-violet-50',
      text: 'text-violet-700',
      border: 'border-violet-200',
      badge: 'bg-violet-100 text-violet-800',
      accent: 'from-violet-600 to-purple-600',
    },
    subcategories: [
      { id: 'railway-station-problems', name: 'Railway Station Problems', description: 'Platform cleanliness, unfunctional escalators, waiting room hygiene & fans', type: 'public_issue', estimatedResolutionTime: '12-24 hours', departmentOrIndustry: 'Railway Division Help' },
      { id: 'railway-services', name: 'Railway-related Services', description: 'Ticket refund queries, passenger assistance for elderly & coach water refill', type: 'service', estimatedResolutionTime: 'Quick assist', departmentOrIndustry: 'Rail Yatri Seva' },
      { id: 'bus-station-problems', name: 'Bus Station Problems', description: 'Broken shed roofing, missing display boards, filthy restroom facilities', type: 'public_issue', estimatedResolutionTime: '24-48 hours', departmentOrIndustry: 'State Road Transport (SRTC)' },
      { id: 'public-transport', name: 'Public Transport', description: 'Missing scheduled buses, rude transit staff, overcharging & route cancellations', type: 'public_issue', estimatedResolutionTime: '24 hours', departmentOrIndustry: 'City Transport Undertaking' },
      { id: 'road-transport', name: 'Road Transport', description: 'Auto-rickshaw/taxi fare refusal, broken traffic signals, speed breaker faults', type: 'public_issue', estimatedResolutionTime: '24-48 hours', departmentOrIndustry: 'Traffic Police & RTO' },
      { id: 'other-transportation', name: 'Other Transportation Problems', description: 'Metro feeder connectivity, cycle track obstructions & parking chaos', type: 'public_issue', estimatedResolutionTime: '2-3 days', departmentOrIndustry: 'Transport Commission' },
    ],
  },
  {
    id: 'government-services',
    name: 'Government Services',
    tagline: 'Public schemes, certificates, welfare programs & document help',
    iconName: 'FileCheck',
    colorScheme: {
      bg: 'bg-rose-50',
      text: 'text-rose-700',
      border: 'border-rose-200',
      badge: 'bg-rose-100 text-rose-800',
      accent: 'from-rose-600 to-pink-600',
    },
    subcategories: [
      { id: 'government-schemes', name: 'Government Schemes', description: 'Eligibility checks, application status for farmer, senior & housing schemes', type: 'government', estimatedResolutionTime: '3-7 days', departmentOrIndustry: 'Public Welfare Department' },
      { id: 'certificates', name: 'Certificates', description: 'Birth, caste, income, domicile, death certificates & verification tracking', type: 'government', estimatedResolutionTime: '3-5 days', departmentOrIndustry: 'Revenue & Tehsildar Office' },
      { id: 'documents', name: 'Documents', description: 'Ration card updates, Voter ID corrections, Land record registry checks', type: 'government', estimatedResolutionTime: '4-7 days', departmentOrIndustry: 'Civic Service Centers' },
      { id: 'public-services', name: 'Public Services', description: 'Pension delays, disability aid, citizen charter complaints & public notary', type: 'government', estimatedResolutionTime: '3-5 days', departmentOrIndustry: 'Social Justice Wing' },
      { id: 'scholarship-services', name: 'Scholarship Services', description: 'Post-matric & pre-matric state schemes, DBT transfer troubleshooting', type: 'government', estimatedResolutionTime: '3-5 days', departmentOrIndustry: 'Minority & Social Welfare' },
      { id: 'local-authority', name: 'Local Authority Services', description: 'Trade licenses, building plan clearances, municipal tax clarifications', type: 'government', estimatedResolutionTime: '3-7 days', departmentOrIndustry: 'Municipal Corporation' },
      { id: 'other-gov-assistance', name: 'Other Government Assistance', description: 'Consumer forum complaints, RTI guidance & grievance escalation', type: 'government', estimatedResolutionTime: '2-5 days', departmentOrIndustry: 'Citizen Redressal Forum' },
    ],
  },
  {
    id: 'utilities',
    name: 'Utilities',
    tagline: 'Power grid, drinking water, gas pipeline & connectivity issues',
    iconName: 'Zap',
    colorScheme: {
      bg: 'bg-cyan-50',
      text: 'text-cyan-700',
      border: 'border-cyan-200',
      badge: 'bg-cyan-100 text-cyan-800',
      accent: 'from-cyan-600 to-blue-600',
    },
    subcategories: [
      { id: 'electricity', name: 'Electricity', description: 'Power outages, fluctuating voltage, transformer spark, faulty meter reading', type: 'utility', estimatedResolutionTime: '2-6 hours', departmentOrIndustry: 'Electricity Distribution Co.' },
      { id: 'water-utility', name: 'Water', description: 'Pipeline bursting, erratic supply timing, pressure drop, valve leakages', type: 'utility', estimatedResolutionTime: '4-12 hours', departmentOrIndustry: 'Water Supply Board' },
      { id: 'gas-utility', name: 'Gas', description: 'Piped natural gas (PNG) disruptions, meter error, emergency odor reporting', type: 'utility', estimatedResolutionTime: '1-3 hours', departmentOrIndustry: 'Gas Distribution Utility' },
      { id: 'internet-connectivity', name: 'Internet/Connectivity', description: 'Fiber cable cuts, broadband exchange downtime & mobile signal blackspots', type: 'utility', estimatedResolutionTime: '4-8 hours', departmentOrIndustry: 'Telecom / ISP Authority' },
      { id: 'other-utility', name: 'Other Utility Problems', description: 'Solar rooftop grid sync failure, rainwater harvesting & street conduit faults', type: 'utility', estimatedResolutionTime: '24 hours', departmentOrIndustry: 'Renewable Energy / Utilities' },
    ],
  },
  {
    id: 'other',
    name: 'Other Everyday Problems',
    tagline: 'General everyday issues, unlisted problems & guidance assistance',
    iconName: 'HelpCircle',
    colorScheme: {
      bg: 'bg-slate-100',
      text: 'text-slate-700',
      border: 'border-slate-200',
      badge: 'bg-slate-200 text-slate-800',
      accent: 'from-slate-600 to-gray-700',
    },
    subcategories: [
      { id: 'general-problem', name: 'General Problem', description: 'Noise pollution in neighborhood, illegal parking, neighborhood mediation', type: 'general', estimatedResolutionTime: '24-48 hours', departmentOrIndustry: 'Community Helpdesk' },
      { id: 'other-service', name: 'Other Service', description: 'Emergency roadside car towing, pet veterinarian, courier misplacement', type: 'general', estimatedResolutionTime: '2-4 hours', departmentOrIndustry: 'Local Services Desk' },
      { id: 'not-sure', name: 'Not Sure Where to Go', description: 'Confused where to report? Submit your issue and Fixora will auto-route it', type: 'general', estimatedResolutionTime: 'Immediate triage', departmentOrIndustry: 'Fixora Smart Triage' },
    ],
  },
];

export const SEARCH_SUGGESTIONS = [
  { label: 'AC is not cooling', categoryId: 'home-personal', subcategoryId: 'ac-repair' },
  { label: 'Road has a large pothole', categoryId: 'public-infrastructure', subcategoryId: 'potholes' },
  { label: 'My scholarship has not arrived', categoryId: 'education', subcategoryId: 'scholarship-problems' },
  { label: 'There is no water supply', categoryId: 'public-infrastructure', subcategoryId: 'water-supply' },
  { label: 'My school certificate is delayed', categoryId: 'education', subcategoryId: 'certificate-document' },
  { label: 'I need a plumber', categoryId: 'home-personal', subcategoryId: 'plumber' },
  { label: 'Street light not working', categoryId: 'public-infrastructure', subcategoryId: 'street-lights' },
  { label: 'Electricity voltage fluctuating', categoryId: 'utilities', subcategoryId: 'electricity' },
];
