import { TrackingRecord, ServiceProfessional, PublicIssueItem } from '../types';

export const SAMPLE_TRACKING_RECORDS: Record<string, TrackingRecord> = {
  'FX-2026-9481': {
    trackingId: 'FX-2026-9481',
    title: 'Severe road pothole causing traffic slowdown',
    category: 'Public Infrastructure',
    subcategory: 'Potholes',
    status: 'in_progress',
    departmentOrProvider: 'Roads & Bridges Wing, Ward 14 PWD',
    reportedDate: 'Yesterday, 10:30 AM',
    updatedDate: 'Today, 08:45 AM',
    estimatedResolution: 'Expected completion within 24 hours',
    location: 'Sector 9 Main Cross Road near Metro Pillar 142',
    timeline: [
      { step: 1, title: 'Problem Reported via Fixora', desc: 'Civic issue recorded with location and severity tag.', timestamp: 'Yesterday, 10:30 AM', completed: true },
      { step: 2, title: 'Automated Department Triage', desc: 'Routed to Public Works Department (Roads Maintenance Div).', timestamp: 'Yesterday, 11:15 AM', completed: true },
      { step: 3, title: 'Ward Officer Assigned & Site Inspected', desc: 'Junior Engineer visited location, asphalt repair vehicle dispatched.', timestamp: 'Today, 08:45 AM', completed: true, current: true },
      { step: 4, title: 'Patching & Final Clearance', desc: 'Surface leveled, road opened for smooth transit.', timestamp: 'Pending closure', completed: false },
    ],
  },
  'FX-2026-3108': {
    trackingId: 'FX-2026-3108',
    title: 'Inverter AC gas leakage & zero cooling',
    category: 'Home & Personal Services',
    subcategory: 'AC Repair',
    status: 'assigned',
    departmentOrProvider: 'CoolTech Solutions (Fixora Certified Partner)',
    reportedDate: 'Today, 09:15 AM',
    updatedDate: 'Today, 09:40 AM',
    estimatedResolution: 'Technician arriving by 02:00 PM today',
    location: 'Apt 402, Green Meadows Residency',
    timeline: [
      { step: 1, title: 'Service Request Confirmed', desc: 'Split AC inspection booked with standard safety checklist.', timestamp: 'Today, 09:15 AM', completed: true },
      { step: 2, title: 'Certified Specialist Allocated', desc: 'Technician Rajesh V. (Rating 4.9★, 8 yrs exp) assigned.', timestamp: 'Today, 09:40 AM', completed: true, current: true },
      { step: 3, title: 'On-Site Diagnostic & Repair', desc: 'Pressure leak test & refrigerant top-up.', timestamp: 'Scheduled: 02:00 PM', completed: false },
      { step: 4, title: 'Job Completion & Guarantee Card', desc: 'Customer signoff & 30-day service warranty.', timestamp: 'Pending', completed: false },
    ],
  },
  'FX-2026-7254': {
    trackingId: 'FX-2026-7254',
    title: 'Post-Matric Scholarship DBT disbursement delay',
    category: 'Education',
    subcategory: 'Scholarship Problems',
    status: 'resolved',
    departmentOrProvider: 'State Higher Education Welfare Cell',
    reportedDate: '3 days ago',
    updatedDate: 'Yesterday, 04:20 PM',
    estimatedResolution: 'Resolved & Disbursed to Bank Account',
    location: 'Government Engineering College Campus',
    timeline: [
      { step: 1, title: 'Grievance Submitted', desc: 'Application reference & bank IFSC mismatch flagged.', timestamp: '3 days ago', completed: true },
      { step: 2, title: 'Nodal Officer Verification', desc: 'Academic records cross-verified with registrar.', timestamp: '2 days ago', completed: true },
      { step: 3, title: 'Direct Benefit Transfer (DBT) Pushed', desc: 'Treasury payment batch approved and processed.', timestamp: 'Yesterday, 02:10 PM', completed: true },
      { step: 4, title: 'Resolution Confirmed', desc: 'Scholarship credited to Aadhaar-seeded account.', timestamp: 'Yesterday, 04:20 PM', completed: true },
    ],
  },
};

export const SAMPLE_SERVICE_PROFESSIONALS: ServiceProfessional[] = [
  {
    id: 'sp-1',
    name: 'Suresh Kumar',
    role: 'Senior Electrician & Inverter Specialist',
    category: 'Electrician',
    rating: 4.9,
    reviewsCount: 312,
    experienceYears: 11,
    verified: true,
    availability: 'Available Today',
    skills: ['MCB Tripping', 'House Rewiring', 'Inverter Setup', 'Appliance Earthing'],
    startingRate: '$20 / hr',
  },
  {
    id: 'sp-2',
    name: 'Anand Sharma',
    role: 'Master Plumber & Pipe Diagnostics',
    category: 'Plumber',
    rating: 4.8,
    reviewsCount: 245,
    experienceYears: 9,
    verified: true,
    availability: 'Available Today',
    skills: ['Concealed Leakages', 'RO & Geyser Lines', 'Bathroom Fixtures', 'Drain Unclogging'],
    startingRate: '$18 / hr',
  },
  {
    id: 'sp-3',
    name: 'Manoj Verma',
    role: 'HVAC & Dual-Inverter AC Technician',
    category: 'AC technician',
    rating: 4.9,
    reviewsCount: 420,
    experienceYears: 12,
    verified: true,
    availability: 'Available Today',
    skills: ['Gas Refill', 'PCB Circuit Repair', 'Jet Pump Washing', 'Compressor Overhaul'],
    startingRate: '$25 / visit',
  },
  {
    id: 'sp-4',
    name: 'Vikram Singh',
    role: 'Precision Carpenter & Furniture Artisan',
    category: 'Carpenter',
    rating: 4.7,
    reviewsCount: 188,
    experienceYears: 7,
    verified: true,
    availability: 'Next Day',
    skills: ['Smart Lock Fitting', 'Modular Kitchen Repair', 'Door Re-alignment', 'Custom Shelves'],
    startingRate: '$22 / hr',
  },
  {
    id: 'sp-5',
    name: 'Priya Devi & Team',
    role: 'Deep Home Cleaning & Sanitization',
    category: 'Cleaner',
    rating: 4.9,
    reviewsCount: 512,
    experienceYears: 6,
    verified: true,
    availability: 'Available Today',
    skills: ['Eco-friendly Steam Clean', 'Kitchen Degreasing', 'Sofa Shampooing', 'Washroom Acid-Free Polish'],
    startingRate: '$35 / session',
  },
  {
    id: 'sp-6',
    name: 'Deepak Rawat',
    role: 'Refrigerator & Washing Machine Expert',
    category: 'Refrigerator technician',
    rating: 4.8,
    reviewsCount: 194,
    experienceYears: 8,
    verified: true,
    availability: 'Available Today',
    skills: ['Front Load Drum Fixes', 'Thermostat Replacement', 'Defrost Timer', 'Motor Capacitor'],
    startingRate: '$22 / visit',
  },
  {
    id: 'sp-7',
    name: 'Ramesh Patel',
    role: 'Interior & Exterior Texture Painter',
    category: 'Painter',
    rating: 4.8,
    reviewsCount: 140,
    experienceYears: 10,
    verified: true,
    availability: 'Next Day',
    skills: ['Damp Proofing', 'Luster Paint', 'Crack Filling', 'Wall Stencils'],
    startingRate: 'Custom Quote',
  },
  {
    id: 'sp-8',
    name: 'Sunita Rao',
    role: 'Home Cook & Nutrition-Focused Chef',
    category: 'Cook',
    rating: 4.9,
    reviewsCount: 160,
    experienceYears: 14,
    verified: true,
    availability: 'On Call',
    skills: ['Regional Cuisine', 'Dietary Customization', 'Hygiene First', 'Family Meal Plans'],
    startingRate: 'Daily / Monthly',
  },
];

export const SAMPLE_PUBLIC_ISSUES: PublicIssueItem[] = [
  {
    id: 'pi-1',
    title: 'Dangerous trench left open after pipeline work on 5th Avenue',
    category: 'Road Problems & Potholes',
    location: '5th Avenue, near Community Library',
    reportedAgo: '2 hours ago',
    upvotes: 42,
    status: 'Inspected',
    icon: 'AlertTriangle',
  },
  {
    id: 'pi-2',
    title: 'Continuous water leakage from main distribution valve',
    category: 'Water Supply & Drainage',
    location: 'Block C Park, South Extension',
    reportedAgo: '4 hours ago',
    upvotes: 29,
    status: 'Work In Progress',
    icon: 'Droplets',
  },
  {
    id: 'pi-3',
    title: 'Overhead streetlights extinguished along 1.2 km pedestrian road',
    category: 'Street Lights',
    location: 'Railway Overbridge Pedestrian Path',
    reportedAgo: '6 hours ago',
    upvotes: 67,
    status: 'Reported',
    icon: 'LightbulbOff',
  },
  {
    id: 'pi-4',
    title: 'Overflowing municipal garbage container attracting stray animals',
    category: 'Garbage & Sanitation',
    location: 'Ward 22 Vegetable Market Junction',
    reportedAgo: '8 hours ago',
    upvotes: 53,
    status: 'Work In Progress',
    icon: 'Trash2',
  },
  {
    id: 'pi-5',
    title: 'Broken platform display & non-operational ramp for wheelchairs',
    category: 'Railway & Bus Stations',
    location: 'Central Inter-City Terminal, Gate 3',
    reportedAgo: '1 day ago',
    upvotes: 88,
    status: 'Inspected',
    icon: 'Train',
  },
];

export const TRUST_BENEFITS = [
  {
    title: 'One Platform',
    desc: 'From a leaky kitchen faucet to a crater on your street, find resolution without juggling a dozen separate helplines.',
    icon: 'Layers',
  },
  {
    title: 'Multiple Categories',
    desc: 'Covering home services, education, civic infrastructure, public transit, utilities, and citizen documentation.',
    icon: 'Grid',
  },
  {
    title: 'Easy Problem Discovery',
    desc: 'Describe your issue in your own everyday words and let Fixora map you straight to the right category in seconds.',
    icon: 'Search',
  },
  {
    title: 'Simple Request Process',
    desc: 'A straightforward 3-minute submission flow that requests only the critical details needed to act.',
    icon: 'CheckCircle2',
  },
  {
    title: 'Service Discovery',
    desc: 'Connect seamlessly with verified skilled tradespeople for home and personal repairs with transparent credentials.',
    icon: 'UserCheck',
  },
  {
    title: 'Request Tracking',
    desc: 'Clear visual progress updates at every stage so you are never left guessing who is handling your problem.',
    icon: 'Compass',
  },
  {
    title: 'User Friendly',
    desc: 'Built for students, working families, elderly citizens, and neighborhood communities alike with clear language.',
    icon: 'HeartHandshake',
  },
  {
    title: 'Responsive on Every Device',
    desc: 'Flawless experience on smartphones, tablets, laptops, and desktop computers with instant load speed.',
    icon: 'Smartphone',
  },
];

export const USER_ROLES_INFO = [
  {
    role: 'citizen' as const,
    title: 'Normal User / Citizen',
    badge: 'Citizens & Families',
    desc: 'Report home issues, public infrastructure problems, track school scholarship queries, and discover vetted local experts.',
    features: ['Quick problem logging', 'Live tracking timeline', 'Service professional booking', 'Community issue upvoting'],
    icon: 'Users',
    theme: 'border-blue-200 bg-blue-50/50 hover:border-blue-400',
  },
  {
    role: 'provider' as const,
    title: 'Service Provider',
    badge: 'Skilled Tradespeople',
    desc: 'Electricians, plumbers, carpenters, and technicians receiving verified local leads and managing incoming service requests.',
    features: ['Verified credential badge', 'Job notifications', 'Flexible scheduling', 'Transparent customer ratings'],
    icon: 'Briefcase',
    theme: 'border-indigo-200 bg-indigo-50/50 hover:border-indigo-400',
  },
  {
    role: 'authority' as const,
    title: 'Department / Authority',
    badge: 'Municipal & Public Bodies',
    desc: 'PWD, Water Boards, Electricity Utilities, Transport bodies, and Education officers managing civic grievances systematically.',
    features: ['Automated ticket dispatch', 'Ward-level analytics', 'Resolution verification', 'Public transparency logs'],
    icon: 'Building2',
    theme: 'border-emerald-200 bg-emerald-50/50 hover:border-emerald-400',
  },
  {
    role: 'admin' as const,
    title: 'Administrator',
    badge: 'Platform Governance',
    desc: 'Fixora network operations oversight, category taxonomy governance, provider verification, and service quality control.',
    features: ['System health metrics', 'Category & tag control', 'User escalation oversight', 'Performance auditing'],
    icon: 'ShieldCheck',
    theme: 'border-purple-200 bg-purple-50/50 hover:border-purple-400',
  },
];
